# Generated by Django 6.0.4 on 2026-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_portfolio', '0003_paper_deadline_paper_evaluation_paper_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='profile',
            name='research_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation_level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
